source :rubygems
source "http://rubygems.org"
source :rubyforge
source "http://gems.rubyforge.org"
source :gemcutter
source "http://gemcutter.org"

gem "em-websocket"

group :development, :test do
  #Meh...colours?
  gem "turn"
  gem "minitest"
end
